### PR TITLE
Configurable hostnames

### PR DESCRIPTION
**Pull request by gpiskas**
- Implemented hostnames config.
- Fixed start.sh a bit.
- Implemented KV Store (in-mem).
- Cleaned & formatted whole codebase.
- Added source formatter config for eclipse. PLEASE USE IT!

### CODE REVIEW

**Comment by aroulin** [comment]
Seems fine for me.

The idea behind the KeyValueStore interface was to create a InMemoryKeyValueStore class that would have implemented the interface. This would emphasize the fact that the InMemoryKeyValueStore is a simplification (and normally would only be temporary). 
I'm fine altough with having a single KeyValueStore class instead.

**Comment by egeyar** [comment]
It looks nice, thank you for the formatting. Can you also briefly explain why you changed the library?

**Comment by gpiskas** [comment]
Oh! Thanks Eclipse! I just did "organize imports" and it used a library called jettison that comes with hadoop and does exactly what we want! No need for external libraries!

Check out the hadoop build path you created for the project. It has literally tons of libs to do anything we want, including a couple JSON libs, like jackson, gson etc...

I strongly suggest we use those :)

EDIT:

Jackson: http://jackson.codehaus.org/
Gson: https://code.google.com/p/google-gson/
Jettison: http://jettison.codehaus.org/

I suggest Jackson that seems to be better in performance.

**Comment by egeyar** [comment]
I asked google for some comparison between java json libraries. Jackson seems pretty good in some comprehensive comparisions which does not include jettison. However, I saw that jackson is better than jettison in general (stackoverflow answers). So let's use jackson.

Thank you George!

**Pull request merged**
