### PR TITLE
DELIVERABLE 2

### PR DESCRIPTION
**Pull request by philemonf**
New features:
- Working MVCC/2PL
- Locking unit with dead lock prevention mechanism
- Dedicated versioning unit for MVCC/2PL.
- Hostname resolution for future cluster runs.
- A lot of tests

Still missing:
- Properly distributed algorithm (only the data is distributed at the moment)
- MVTO (coming soon, in test phase at the moment...)
- 2PC
- Benchmarks
- An improved test framework (coming soon too, in debug phase)
- Some nice slides ;)

### CODE REVIEW

**Comment by pokitoz** [comment]
Hello! 
The first execution everything worked well.

I exited the application using :exit
15/04/28 22:58:56 INFO yarn.Client: All tests passed for VersioningUnitTest

> :exit
> 15/04/28 22:59:03 INFO yarn.Client: Stopping gracefully application_1430254635498_0001
> 15/04/28 22:59:05 INFO yarn.Client: Application Stopped

However, the second time I launched it I get no error but I have this:

> 15/04/28 23:02:27 INFO yarn.Client: Initializing...
> 15/04/28 23:02:29 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032
> 15/04/28 23:02:29 INFO yarn.Client: Submitting application_1430254635498_0003
> 15/04/28 23:02:29 INFO impl.YarnClientImpl: Submitted application application_1430254635498_0003
> 15/04/28 23:02:29 INFO mortbay.log: Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
> 15/04/28 23:02:29 INFO mortbay.log: Waiting for AppMaster hostname
> 15/04/28 23:02:32 INFO mortbay.log: Waiting for AppMaster hostname
> 15/04/28 23:02:35 INFO mortbay.log: Waiting for AppMaster hostname
> 15/04/28 23:02:38 INFO mortbay.log: Waiting for AppMaster hostname
> ....

and it does not stop.

**Comment by gpiskas** [comment]
Since we removed the zombie killing code from the script, make sure AppMaster and/or TransactionManager is not running.

To veryfy, run 'jps'. Kill any living thing with 'kill -9 PID'

**Comment by pokitoz** [comment]
I did it, but now I get

> java.io.FileNotFoundException: File does not exist: /projects/transaction-manager/config/slaves
> Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /projects/transaction-manager/config/slaves

**Comment by gpiskas** [comment]
I fixed the previous bug, but I don't know about this one. Do you have this file locally so that the script copies in into hadoop?

EDIT: Try restarting yarn and hdfs

**Comment by aroulin** [comment]
Same here with full restart and I have the file locally

**Comment by pokitoz** [comment]
Yes I have it locally. 
I restarted my machine and it works fine the first time and after I get the same problem with the file not found.
I restarted yarn and dfs and same exception.

**Comment by sachinbjohn** [comment]
Some exception while exiting..
Copied from logs

15/04/28 23:20:07 INFO appmaster.AppMaster: Unregistered
15/04/28 23:20:07 INFO impl.ContainerManagementProtocolProxy: Opening proxy : John-pc:54997
15/04/28 23:20:07 INFO impl.AMRMClientImpl: Waiting for application to be successfully unregistered.
15/04/28 23:20:07 INFO impl.AMRMClientAsyncImpl: Interrupted while waiting for queue
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2017)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2052)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:274)

**Comment by gpiskas** [comment]
@sachinbjohn Pull the latest commit!

**Comment by philemonf** [comment]
To check if a port is used, use `lsof -iTCP:{PORT_NUMBER}`.

You might then kill the process owning the port.

And by the way: `yarn application -kill {appId}` might be used too and `yarn application -list` to see the running ones.

For the slaves error, please print here the output of `hdfs dfs -ls /projects/transaction-manager`.

**Comment by aroulin** [comment]
$ hdfs dfs -ls /projects/transaction-manager
Found 1 items
drwxr-xr-x   - andy supergroup          0 2015-04-28 23:34 /projects/transaction-manager/config
$ hdfs dfs -ls /projects/transaction-manager/config
[No output]

**Comment by philemonf** [comment]
And inside ?

**Comment by philemonf** [comment]
Guys, please remove the `exec 3>&2 2>/dev/null` and the `exec 2>&3` from `start.sh` and tell us if you see errors on the console while restarting the application. I personally think that they should be removed on a regular basis.

**Comment by pokitoz** [comment]
Yep, 

> Putting TKVS.jar and config in HDFS...
> 15/04/28 23:42:31 WARN hdfs.DFSClient: DataStreamer Exception
> org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /projects/transaction-manager/TKVS.jar._COPYING_ could only be replicated to 0 nodes instead of minReplication (=1).  There are 0 datanode(s) running and no node(s) are excluded in this operation.
> 
> copyFromLocal: File /projects/transaction-manager/config/slaves._COPYING_ could only be replicated to 0 nodes instead of minReplication (=1).  There are 0 datanode(s) running and no node(s) are excluded in this operation.

Same error if I try on my own to add the file:

> pokitoz@pokitoz-K56CB:~/Desktop/GIT/transactional-key-value-store-project$ hdfs dfs -ls /projects/transaction-manager/config/slaves
> ls: `/projects/transaction-manager/config/slaves': No such file or directory
> pokitoz@pokitoz-K56CB:~/Desktop/GIT/transactional-key-value-store-project$ hdfs dfs -put ./config/slaves /projects/transaction-manager/config/slaves
> 15/04/28 23:39:29 WARN hdfs.DFSClient: DataStreamer Exception
> org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /projects/transaction-manager/config/slaves._COPYING_ could only be replicated to 0 nodes instead of minReplication (=1).  There are 0 datanode(s) running and no node(s) are excluded in this operation.

**Comment by philemonf** [comment]
@pokitoz Apparently you killed your whole HDFS setup (no datanodes are running). You shouldn't be able to access hdfs with the `hdfs` command.

**Comment by philemonf** [comment]
@pokitoz Did you try `./sbin/stop-all.sh && ./sbin/start-all.sh` from the Hadoop folder? If yes, please restart your machine physically.

**Comment by aroulin** [comment]
Good for me now with the help of a physical restart.

**Comment by pokitoz** [comment]
Same, its working now :) 
For no reason the last physical restart did not work...
Anyway now it's good for me

**Comment by philemonf** [comment]
Do we merge?

**Comment by gpiskas** [comment]
yes

**Pull request merged**
