### PR TITLE
Better networking

### PR DESCRIPTION
**Pull request by gpiskas**
- No need for port assignment by hand. Automatically assigns ports to everything that needs one.
- No hard-coded ports.
- No need for localinit.sh. Use "start.sh local" once at the beginning.
- Easier for AMThread to reply to TM requests.

### CODE REVIEW

**Comment by sachinbjohn** [comment]
There should be mechanism for not just AM , but also TMs to know about hostname:port of other TMs. (as well as AM). But you removed the getTMbyHash(int hash)  method from NetConfig. What should I do to get this information?

**Comment by gpiskas** [comment]
You are right, I forgot about TM to TM comm. I will add that functionality when I get back home.

**Comment by philemonf** [comment]
Ok! Let's wait for this feature before merging. Let's discuss those steps after the meeting.

**Comment by gpiskas** [comment]
Just updated. Check it out guys, and if it works, we merge.

EDIT: Remember to run "./start.sh local", to update the slaves file.

**Comment by philemonf** [comment]
It works for me. Good job!

**Comment by pokitoz** [comment]
Works for me :)

**Comment by aroulin** [comment]
Works for me too. I'm fine with the modifications.

**Pull request merged**
