### PR TITLE
Even more refactoring

### PR DESCRIPTION
**Pull request by philemonf**
This is a continuation of the refactoring made by Georges.

The main points:
- Usage of Base64 for the transfer to respect the JSON standards.
  - In that way, all on the "server-side" are Base64 strings (this can be changed in a matter of seconds).
  - The client can use any serializable he wants.
- Standardized message coding: One just declares a class representing a class representing a request and the parsing is deduced from it.
- Configuration file with port to specify the cluster configuration.
- Add thread pool for scalability.

That's pretty much it.

### CODE REVIEW

**Comment by pokitoz** [comment]
The source code does not seem to be formatted properly.

Also, I get the following error: 

  Client REPL:

> :test
>   Running test client...
>   User Client starting
>   Couldn't get I/O for the connection to localhost:9999
>   java.net.ConnectException: Connection refused

I tried to restart yarn, change the ports but nothing changed. Maybe some ports are not freed.

One last thing, in the AMWorker, the BufferedReader (named "in") and the Socket (named "sock") should be closed in a finally block.

**Comment by aroulin** [comment]
I tried quickly and I am unable to `:test` it correctly. It complains about the ports too.
I tried without success to change the different ports. In case of exceptions/crash, the ports do not seem to be released.

Anyone else having problems ?

**Comment by gpiskas** [comment]
The :test works for me.
Try ./start.sh and then when the REPL is ready, wait for a few seconds (10?) for the AM and TMs to fully start. We will fix that by delaying the REPL to show up until everything is up and running. Or maybe there will be no REPL later, so let's just leave it like this for now I think.

BTW: From my refactoring part, I said we should implement graceful stop. That is what is missing. For now I am just killing zombies in start.sh (dirty), and maybe that's why ports are reserved.

**Comment by aroulin** [comment]
I tried waiting without success, I get the same exception.

**Comment by pokitoz** [comment]
Me too.

**Comment by philemonf** [comment]
Did you guys try changing the ports in the config file?

**Comment by pokitoz** [comment]
Yes. But still the same exception. Did you change something in your configuration of yarn?

**Comment by philemonf** [comment]
Nope. It is running perfectly fine on my machine, even under stress...

**Comment by philemonf** [comment]
Can you guys paste the log in here?

**Comment by gpiskas** [comment]
I implemented graceful stop. Use ":exit" from now on instead of ":kill". Nonetheless, the "walking dead" code is still there just in case...
Chances of it working for both of you are higher now :facepunch:

**Comment by philemonf** [comment]
Do you guys have the same?

$ cat etc/hadoop/hdfs-site.xml 
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>



<configuration>
  <property>
    <name>dfs.replication</name>
    <value>1</value>
  </property>
</configuration>

$ cat etc/hadoop/yarn-site.xml
<?xml version="1.0"?>

<configuration>
  <property>
    <name>yarn.nodemanager.aux-services</name>
    <value>mapreduce_shuffle</value>
  </property>
</configuration>

$ cat etc/hadoop/core-site.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>



<configuration>
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://localhost:9000</value>
  </property>
</configuration>
Philemons-MacBook-Air:libexec phil$

**Comment by aroulin** [comment]
Works now for both of us.

**Comment by pokitoz** [comment]
Good for me!
:)

**Pull request merged**
