### PR TITLE
DELIVERABLE 3

### PR DESCRIPTION
**Pull request by gpiskas**
This PR includes the following feature:
- The simple 2PL algorithm (without multi-version);
- Distributed concurrency control (2PC);
- Cooperation between the TransactionManager;
- A random but still configurable benchmarking system;
- A modular centralized decision system that includes:
  - Distributed dead-lock detection for (MVCC)2PL
  - Distributed garbage collection of versions for MVTO
- A test framework for concurrent transaction schedule testing.

### CODE REVIEW

**Comment by sachinbjohn** [comment]
Not Ready!

**Comment by gpiskas** [comment]
Do not worry! You can keep committing on the RemoteHandlerClean and commits will show up here too. :)

**Comment by philemonf** [comment]
Not ready :P! Please don't stress people haha! You are stressing me with your PR!

**Comment by philemonf** [comment]
Furthermore, it need to be merged with benchmarking before. Let's do the merge on Monday together.

**Comment by aroulin** [comment]
In fact this branch is currently up-to-date with the benchmarking branch.

**Comment by philemonf** [comment]
Good news!

**Pull request merged**
